CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR CHECK (name <> '') NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER CHECK (duration > 0),
    genre_id     INTEGER                    REFERENCES genres (id) ON DELETE SET NULL,
    mpa_id       INTEGER                    REFERENCES mpas (id) ON DELETE SET NULL,
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR CHECK (login <> '') NOT NULL UNIQUE,
    name     VARCHAR,
    email    VARCHAR                     NOT NULL UNIQUE,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR CHECK (name <> '') NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpas
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR CHECK (name <> '') NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    from_user INTEGER REFERENCES users (id) ON DELETE CASCADE,
    to_user   INTEGER REFERENCES users (id) ON DELETE CASCADE,
    status    VARCHAR CHECK (status IN ('pending', 'accepted', 'declined')),
    PRIMARY KEY (from_user, to_user),
);
